[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "87a35a1bcbaffbd225cc1d70deaa208a8e9acc0b"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 增加左键点击复制文本的功能
- 增加CID显示（默认关闭，在设置里开启）
"""
